spring.application.name=M360-Task-1
spring.datasource.url=jdbc:postgresql://localhost:5432/M360
spring.datasource.username=postgres
spring.datasource.password=madan1430

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

spring.web.error.include-message=always

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationWhichShouldBeLongEnough123456
jwt.expiration=86400000

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Enable Liquibase
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.drop-first=true


# PGVECTOR
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=384
spring.ai.vectorstore.pgvector.initialize-schema=true

# Google Gemini AI
spring.ai.google.genai.api-key=AIzaSyBEmSwXfJgAduPHvq8UY0iMeyo5kOXKAVY
#spring.ai.google.genai.api-key=AIzaSyACBvpxb3nBNGrmCUWi_UWZ_svs2ZrUimk
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.4
spring.ai.retry.max-attempts=1

spring.ai.google.genai.embedding.enabled=true
spring.ai.google.genai.embedding.api-key=${spring.ai.google.genai.api-key}
spring.ai.google.genai.embedding.text.options.model=text-embedding-004

spring.servlet.multipart.enabled=true
spring.servlet.multipart.resolve-lazily=true

logging.level.org.springframework.ai.tool=DEBUG
logging.level.org.springframework.ai.chat.client=DEBUG